### ISSUE TITLE
Picking up an item pushes the character backwards (BUG)

### ISSUE THREAD

**Issue by Szetoo** [olejarza/VACATe#136]
**1. Description of bug**

Context: I was trying to pick up the rock in the tutorial level and noticed that it pushed me backwards. If I do not move and constantly pick up then drop the rock, my character would proceed to move backwards little by little. 

Expected Output: I was expecting that upon picking up the rock my character would not get displaced.

Actual Output: The character moves backwards little by little.

**2. Minimal steps to reproduce**

i) Go to main menu.
ii) Load tutorial level
iii) Control pink player and move to pink rock
iv) Without moving, pick up rock
v) Without moving, drop rock
vi) Repeat steps iv. and v. multiple times

**3. Appearance of bug**

This bug appeared on every rock that I tried picking up and this behaviour was reproduced for both players in the tutorial level.

**4. System configuration**

Resolution: 1366x768, Full Screen
OS: Windows 8.1
Graphics Quality: Very Low
Specs: Intel(R) Core i7-5500U CPU @ 2.40GHz, Intel(R) HD Graphics 5500, 64 bit, 12 GB RAM

**5. Suggested Solution**

Make it so that when an item gets picked up, it becomes a child game object of the player and its transform gets an offset based on the player. This probably occurs because of colliders and the rock physically pushing the character back.

**Comment by tommy-tran** [comment]
Kinda similar to #171
