### ISSUE TITLE
Sound gets repeated but highlight doesn't get removed when successively placing the correct coloured block in the correct spot (BUG)

### ISSUE THREAD

**Issue by Szetoo** [olejarza/VACATe#137]
**1. Description of bug**

Context: FIRST STAGE OF THE TUTORIAL LEVEL - I was placing the correct coloured rock onto the right spot (picture attached at the end) and when taking it off, the highlight did not disappear but when I placed the rock again, the sound played.

Expected Output: I was expecting either the highlight to disappear and the sound to play OR the highlight to not disappear and the sound to not play OR the rock to not be able to be picked up after being placed so that this never occurs.

Actual Output: The highlight does not disappear and the sound gets played again when the rock is placed again.

**2. Minimal steps to reproduce**

i) Go to main menu.
ii) Click new game
iii) Play tutorial level
iv) Control green player
v) Pick up rock and bring it to the green zone (top left corner) and drop it
vi) Pick up rock again and drop it in the same spot.

**3. Appearance of bug**

This bug appeared everytime and occurred for both players.

**4. System configuration**

Resolution: 1366x768, Full Screen
OS: Windows 8.1
Graphics Quality: Very Low
Specs: Intel(R) Core i7-5500U CPU @ 2.40GHz, Intel(R) HD Graphics 5500, 64 bit, 12 GB RAM

![image](https://user-images.githubusercontent.com/33875910/71647932-3c4ec580-2ccb-11ea-9af5-746ada19911d.png)

**Comment by nessa-art** [comment]
Mechanism was working at some point - labelling as a regression.
