### ISSUE TITLE
On third stage of the tutorial level, game crashed when one player fights the two enemies in the bottom right and the other player is in the middle (BUG - GAME CRASH)

### ISSUE THREAD

**Issue by Szetoo** [olejarza/VACATe#140]
**1. Description of bug**

Context: I was trying to fight the enemies on the third stage of the tutorial level. Green player was right in between the two enemies in the bottom right corner. Pink player was in the middle of the stage. 

Expected Output: I was expecting the game to proceed normally and to continue fighting the enemies.

Actual Output: The game crashed and brought me back to the main menu.

**2. Minimal steps to reproduce**

i) Go to main menu.
ii) Click on new game.
iii) Click on play
iv) Get to stage 3 of the tutorial level.
v) Place the green player in between the two enemies at the bottom right.
vi) Place the pink player in the middle of the stage.

**3. Appearance of bug**

This bug appeared everytime I tried it and worked for either player as it did not matter which player was fighting the enemies or which player was in the middle.

**4. System configuration**

Resolution: 1366x768, Full Screen
OS: Windows 8.1
Graphics Quality: Very Low
Specs: Intel(R) Core i7-5500U CPU @ 2.40GHz, Intel(R) HD Graphics 5500, 64 bit, 12 GB RAM

![image](https://user-images.githubusercontent.com/33875910/71648684-6e652500-2cd5-11ea-9de6-9bbf4b2890b2.png)

PUT PLAYERS IN THESE TWO SPOTS AND THE GAME CRASHES

![image](https://user-images.githubusercontent.com/33875910/71648700-a2d8e100-2cd5-11ea-8071-c3027365190f.png)

**Comment by trudeaua** [comment]
Fixed in #240
