### ISSUE TITLE
Player does not respawn when it dies in the tutorial stage (BUG)

### ISSUE THREAD

**Issue by Szetoo** [olejarza/VACATe#141]
**1. Description of bug**

Context: I was fighting the enemies on the third stage of the tutorial level and died.

Expected Output: I was expecting that when I die in a tutorial stage that my character would respawn OR if both players died, the stage would restart.

Actual Output: The players did not respawn and nothing happened to the game state. I could not progress any further.

**2. Minimal steps to reproduce**

i) Go to main menu.
ii) Click on new game.
iii) Click on play.
iv) Get to stage 3
v) Die to enemy
vi) Both players die to enemy

**3. Appearance of bug**

This bug appeared everytime I tried it.

**4. System configuration**

Resolution: 1366x768, Full Screen
OS: Windows 8.1
Graphics Quality: Very Low
Specs: Intel(R) Core i7-5500U CPU @ 2.40GHz, Intel(R) HD Graphics 5500, 64 bit, 12 GB RAM

**Comment by tommy-tran** [comment]
#106
