### ISSUE TITLE
Cannot get back to the main menu or exit game with controller (BUG)

### ISSUE THREAD

**Issue by Szetoo** [olejarza/VACATe#142]
**1. Description of bug**

Context: I was trying to exit the game using the controller.

Expected Output: I was expecting that pressing the options button or any button would let me quit.

Actual Output: None of the buttons allowed for me to quit. I could only quit by clicking the x button or closing the entire game.

**2. Minimal steps to reproduce**

i) Go to main menu.
ii) Click on new game.
iii) Click on play.
iv) Try to exit game with controller or return to main menu.

**3. Appearance of bug**

This bug appeared everytime I tried.

**4. System configuration**

Resolution: 1366x768, Full Screen
OS: Windows 8.1
Graphics Quality: Very Low
Specs: Intel(R) Core i7-5500U CPU @ 2.40GHz, Intel(R) HD Graphics 5500, 64 bit, 12 GB RAM

**Comment by trudeaua** [comment]
Will be fixed with #138
