### ISSUE TITLE
Player can't return after going off stage (BUG)

### ISSUE THREAD

**Issue by Szetoo** [olejarza/VACATe#144]
**1. Description of bug**

Context: I was trying play through the first level.

Expected Output: I was expecting that upon going off the edge, I would either fall off or die.

Actual Output: I went out of bounds but did not fall completely or die and I could not return back.

**2. Minimal steps to reproduce**

i) Go to main menu.
ii) Click on new game
iii) Click on skip
iv) Walk off

**3. Appearance of bug**

This bug appeared everytime I tried to exit by clicking the exit button on the main menu.

**4. System configuration**

Resolution: 1366x768, Full Screen
OS: Windows 8.1
Graphics Quality: Very Low
Specs: Intel(R) Core i7-5500U CPU @ 2.40GHz, Intel(R) HD Graphics 5500, 64 bit, 12 GB RAM

**Comment by tommy-tran** [comment]
Going to point this to #106
