### ISSUE TITLE
Color combination puzzle (BUG)

### ISSUE THREAD

**Issue by AlexanderPattison** [olejarza/VACATe#147]
1. Description of bug 
• Context – When in the first game level, before the first gate, the combination puzzle does not accept the correct 'PGGP' color combination following an incorrect combination.
• Expected output – Entering PGGP after incorrectly flipping switches opens the gate.
• Actual output – Does not open the gate.
 
2. Minimal steps to reproduce 
 • flip the green 'G' switch once
• flip the 'PGGP' combination

3. Appearance of bug
Isolated to the color combination puzzle. 
 
4. System configuration
• Very low quality, 1080 x 1920, Full-screen
• Windows 10
• 64-bit, Intel CPU, 32GB RAM
• PS3, using driver: SCP-DS-Driver-Package-1.2.0.160

**Comment by nessa-art** [comment]
Fixed in #211
