### ISSUE TITLE
Color zone returns to off state when removing it's stone (Suggestion)

### ISSUE THREAD

**Issue by AlexanderPattison** [olejarza/VACATe#148]
1. Description of Requested Feature/Change to Existing Feature
Context: Solving the rock and zone color co-ordination challenges.
High level feature explanation: Removing a rock from a color matched zone will return the zone to it's original off-state.

2. Rationale/Justification of Feature
Solving the puzzle requires the player to pair a zone and rock of matching color. Therefore, removing a stone from it's color matched zone should return the zone to it's original off state.

3. Suggested Solutions
Store the number of matching rocks in the zone. Update this value upon placement and removal. Change the zone state when there are one or more rocks in the zone.

**Comment by nessa-art** [comment]
Addressed this issue from PR #243
