### ISSUE TITLE
Unmovable stone (BUG)

### ISSUE THREAD

**Issue by AlexanderPattison** [olejarza/VACATe#149]
1. Description of bug
• Context – When in the game level, attempting to pick up the rock in the purple color zone.
• Expected output – Player holds the rock
• Actual output – The player animation for pickup and drop occurs, but without changes to the rock.
 
2. Minimal steps to reproduce 
• load into the game level
• attempt to pick up the rock in the first purple color zone
 
3. Appearance of bug
This bug occurs to all non color matching rocks.
 
4. System configuration
• Very low quality, 1080 x 1920, Full-screen
• Windows 10
• 64-bit, Intel CPU, 32GB RAM
• PS3, using driver: SCP-DS-Driver-Package-1.2.0.160

5. Suggestion
Use player animations for picking up and putting down valid moveable rocks.
Create a another animation, or sound, to indicate that the rock is not valid. Perhaps an animation for attempting.

**Comment by trudeaua** [comment]
Fixed in #241
