### ISSUE TITLE
Game does not progress when falling off into the void (BUG)

### ISSUE THREAD

**Issue by AlexanderPattison** [olejarza/VACATe#150]
1. Description of bug
• Context – When in the game level, walking off the game platform and into the void.
• Expected output – respawn, or end game
• Actual output – endless falling, and walking around underneath the map
 
2. Minimal steps to reproduce 
• load into the game level
• walk off the edge of any platform
 
3. Appearance of bug
This bug occurs when the a player walks off any platform in the game level.
 
4. System configuration
• Very low quality, 1080 x 1920, Full-screen
• Windows 10
• 64-bit, Intel CPU, 32GB RAM
• PS3, using driver: SCP-DS-Driver-Package-1.2.0.160

5. Suggestion
• Add a falling into void animation to the player, and add a respawn point or restart the level.

**Comment by AlexanderPattison** [comment]
The players can fall off into the void from all other platforms, not just the bridges. The game is still unplayable after this point.

**Comment by trudeaua** [comment]
Same as #144
