### ISSUE TITLE
Tutorial play and skip buttons (BUG)

### ISSUE THREAD

**Issue by AlexanderPattison** [olejarza/VACATe#151]
1. Description of bug
• Context – When trying to click the skip button after miss-clicking the play button
• Expected output – enter either the tutorial or game
• Actual output – game freezes in the game level
 
2. Minimal steps to reproduce 
• click the play button
• click the skip button before the tutorial begins
 
3. Appearance of bug
This bug is isolated to the menu screen.
 
4. System configuration
• Very low quality, 1080 x 1920 
• Windows 10
• 64-bit, Intel CPU, 32GB RAM
• PS3, using driver: SCP-DS-Driver-Package-1.2.0.160

**Comment by trudeaua** [comment]
Same root cause as #139
