### ISSUE TITLE
Balance the damage output of certain weapons (SUGGESTION)

### ISSUE THREAD

**Issue by Szetoo** [olejarza/VACATe#154]
**1. Description of Requested Feature/Change to Existing Feature**

Context: I was trying to fight the enemies as the archer class.

High level feature explanation: Increase the damage of the archer's basic attack (shooting bow). It felt very ineffective and took a long time to damage/kill enemies in comparison to the fire mage (pink character).

**2. Rationale/Justification of Feature**

It's an interesting aspect to have different characters specialize in different fighting styles so there's definitely a benefit to making certain classes weaker. However, it felt like the archer class was harder to use than the fire mage as it was way easier to hit enemies with the fire in comparison to hitting them with a bow an arrow. Therefore, if the damage numbers were changed, the noticeably different fighting styles can be maintained but skilled gameplay is also more accurately rewarded.

**3.  Suggested Solutions**

Since the first attack costs less mana than the second attack, perhaps make the scaling ratio of mana cost to damage consistent for all characters. Also, it may help to make a character's damage match their difficulty of usage (harder = more damage).

**Comment by tommy-tran** [comment]
Overlap #251
