### ISSUE TITLE
Adjust hitbox for fire attack of fire mage (SUGGESTION)

### ISSUE THREAD

**Issue by Szetoo** [olejarza/VACATe#158]
**1. Description of Requested Feature/Change to Existing Feature**

Context: I was trying to fight boss Mini Legion Lich and I was controlling the pink character.

High level feature explanation: Make it so that the hitbox for the fire matches the size of the fire that the player sees. The boss was inside the fire but it was not taking any damage until it got really close.

**2. Rationale/Justification of Feature**

Fighting the boss was strange because the damage was not matching the size of the attack. Making the hitbox match the size of the flames would make the experience playing that character a lot more enjoyable. 

**3.  Suggested Solutions**

Either increase the size of the hitbox for the flame or decrease the size of the flame to match the current hitbox.

**Comment by tommy-tran** [comment]
Will be included in #251
