### ISSUE TITLE
Add HUD with player abilities and cooldowns (SUGGESTION)

### ISSUE THREAD

**Issue by Szetoo** [olejarza/VACATe#160]
**1. Description of Requested Feature/Change to Existing Feature**

Context: I was trying to use the various abilities of the characters.

High level feature explanation: Add a HUD with the player's abilities represented as icons and make them grey when they are on cooldown. Their mana cost can also be displayed on here. The abilities could be bordered with the colour of the player that they belong to as well.

**2. Rationale/Justification of Feature**

I believe that this feature would give players a clearer understanding of their abilities and also the abilities of other players. It's also classic approach to coop games that have multiple players. The health/mana bars could also be displayed here if desired.

**3.  Suggested Solutions**

Implement a HUD with each character's abilities and they could be bordered with the colour of the player that they belong to as well. Potentially add hp/mana bars here to clear up clutter on the main screen and add cooldown indicators / mana costs for each ability.

**Comment by tommy-tran** [comment]
Not intended to have cd indicators but rather mana/energy management. Will have no HUD for less clutter
