### ISSUE TITLE
Game becomes softlocked once both players die (BUG)

### ISSUE THREAD

**Issue by tdykstra123** [olejarza/VACATe#163]
1. Description of bug

Context: I let a scorpion kill both players in the first level

Expected Output: Game over screen, return to main menu

Actual Output: Nothing. No way to return to main menu, so game becomes stuck.

2. Minimal steps to reproduce

i) Go to Level 1
ii) Reach the second stage, with the enemies
iii) Let both players die

3. Appearances
This is a common problem in both the tutorial and level 1, and happens with any enemy.

4. Potential Fix(es)
 
-Add a game over screen
-Add a way for the player to return to the main menu
-Add a way for the player to return to the beginning of the level/checkpoint

5. System configuration

Resolution: 1920x1080, Full Screen
OS: Windows 10.1
Graphics Quality: Very Low
Specs: Intel(R) Core i7-5500U CPU @ 2.40GHz, NVIDIA GEFORCE, 64 bit, 12 GB RAM

**Comment by tommy-tran** [comment]
#250 encompassed by game over state implementation
