### ISSUE TITLE
Players start slowly sinking after walking off stage in first level (BUG)

### ISSUE THREAD

**Issue by tdykstra123** [olejarza/VACATe#164]
Description of bug
Context: I had just loaded the first level, and attempted to walk off-stage

Expected Output: Player either hits invisible wall, or dies

Actual Output: Player walks off into space, visibly starts sinking. Can return to playing field if quick enough, otherwise gets stuck on solid floor. Eventually is able to run underneath the level.

Minimal steps to reproduce
i) Go to main menu.
ii) Go to load
iii) Go to Skip
iv) Once game starts, walk off the opening platform

Appearances:
Happens with every pit I could find in both tutorial and level 1

Potential Fix(es):
-Add invisible walls so the player cannot leave the designated zone

System configuration
Resolution: 1920x1080, Full Screen
OS: Windows 10.1
Graphics Quality: Very Low
Specs: Intel(R) Core i7-5500U CPU @ 2.40GHz, NVIDIA GEFORCE, 64 bit, 12 GB RAM

**Comment by trudeaua** [comment]
Pretty much the same issue as #144
