### ISSUE TITLE
Add a way to return to main menu after clicking "New" (SUGGESTION)

### ISSUE THREAD

**Issue by tdykstra123** [olejarza/VACATe#165]
Description of Requested Feature/Change to Existing Feature
Context: I clicked on new and wanted to return to the main menu, but there was no option to do so.

High level feature explanation: There needs to be a way for the player to return to the main menu

Rationale/Justification of Feature
It was really annoying, knowing that I was stuck and forced to play either the tutorial or the first level.

Suggested Solutions
-Add a "Back" button, like what exists from the "Load" menu

**Comment by trudeaua** [comment]
Fixed in #244
