### ISSUE TITLE
Player cannot interact with objects while stuck in "carrying" state (BUG)

### ISSUE THREAD

**Issue by tdykstra123** [olejarza/VACATe#167]
Description of bug
Context: After finding the previous bug where players would attempt to pick up objects that they couldn't (leaving them in the "carrying" state), I was experimenting with what I can and can't do in this state.

Expected Output: Unable to do anything useful in this state

Actual Output: Could walk around, could attack. Always reverted back to this state. Pressing the "drop" button leaves this state. Players cannot interact with objects until leaving this state.

Minimal steps to reproduce
i) Go to Level 1
ii) Attempt to pick up a differently coloured rock, entering the "carrying" animation state
iii) Attempt to pick up a similarly coloured rock while still in this state.

Appearances:
Happened every time I tried it. Since hitting the interact button again makes the player leave this state, relatively minor bug.

Potential Fix(es):
Fixing the "carrying" state bug in the first place should fix this one by extension.

System configuration
Resolution: 1920x1080, Full Screen
OS: Windows 10.1
Graphics Quality: Very Low
Specs: Intel(R) Core i7-5500U CPU @ 2.40GHz, NVIDIA GEFORCE, 64 bit, 12 GB RAM

**Comment by trudeaua** [comment]
Fixed in #241
