### ISSUE TITLE
Dialogue does not play after leaving to main menu, going back into tutorial (BUG)

### ISSUE THREAD

**Issue by tdykstra123** [olejarza/VACATe#169]
Description of bug
Context: After encountering a game crash (?) in stage 3 of the tutorial, I returned to the tutorial

Expected Output: Everything behaves the same as when you first open the tutorial

Actual Output: Dialogue boxes no longer showed up

Minimal steps to reproduce
i) Go to Tutorial
ii) Reach stage 3, encounter crash back to main menu
iii) Re-enter the tutorial

Appearances
I performed the Tutorial crash twice (relaunching the game between attempts), and it happened both times. It also persists into level 1, denying the player of crucial hints.

Potential Fix(es):
-Fix the tutorial stage 3 crash
-Ensure that the dialogue box state is properly reset once the player returns to the main menu

System configuration
Resolution: 1920x1080, Full Screen
OS: Windows 10.1
Graphics Quality: Very Low
Specs: Intel(R) Core i7-5500U CPU @ 2.40GHz, NVIDIA GEFORCE, 64 bit, 12 GB RAM

**Comment by trudeaua** [comment]
Same root problem as #139
