### ISSUE TITLE
Non-cosmetic enemies can walk onto teleporter bridge, soft-locking the game (BUG)

### ISSUE THREAD

**Issue by tdykstra123** [olejarza/VACATe#172]
Description of bug
Context: I was at the second part of the second level, where you see the bridge full of teleporting scorpions. One started chasing the purple player, and he ran off the edge of the map by mistake, and onto the bridge in the background.

Expected Output: Defeating all the enemies and/or pulling both levers would continue the game.

Actual Output: The scorpion pursued the player onto the bridge, and ended up stuck there. 

Minimal steps to reproduce
i) Go to Level 1
ii) Reach the second part of the second puzzle
iii) Get an enemy to chase you
iv) Run onto the bridge
v) Once on the bridge, hit the teleporter and quickly run back to the main platform. The game has been softlocked.

Appearances:
This seems to be specific to the teleporter bridge. Sometimes, the original scorpion you have to kill actually spawns on the bridge, and is seemingly impossible to kill while there.

Potential Fix(es):
-Ensure the scorpions all spawn on the platform
-Fix the issue where players/enemies can walk off the platforms in the first place

System configuration
Resolution: 1920x1080, Full Screen
OS: Windows 10.1
Graphics Quality: Very Low
Specs: Intel(R) Core i7-5500U CPU @ 2.40GHz, NVIDIA GEFORCE, 64 bit, 12 GB RAM

**Comment by tommy-tran** [comment]
#249
