### ISSUE TITLE
Tutorial puzzle one improvement (Suggestion)

### ISSUE THREAD

**Issue by JiaanZhang** [olejarza/VACATe#178]
The rectangular gate behind several blue stones is not necessary. The blue stone can block the player to enter the next level. It makes more sense that before each player has picked their own coloured stone and put them into right place, the blue stones are not pickable. Only after the puzzle is solved, the player can move away the blue stones and enter next level.

**Comment by tommy-tran** [comment]
Tutorial Redesign #249 will cover this issue
