### ISSUE TITLE
"PGGP" hint improvement (Suggestion)

### ISSUE THREAD

**Issue by JiaanZhang** [olejarza/VACATe#181]
Do not leave too many non-trivial crystal in the first level otherwise player will be very confused with the meaning of ‘PGGP’. I thought you want us to put pink and green crystal on the respective letters, since there are a lot pink and green stones. But the real purpose of these letters is to let the players know the order to trigger the lever.

**Comment by tommy-tran** [comment]
Will be simplifying puzzles and focusing more on combat based challenges
