### ISSUE TITLE
Player can pass level 3 tutorial without killing the enemy(Bug)

### ISSUE THREAD

**Issue by JiaanZhang** [olejarza/VACATe#184]
In tutorial 3, we can see there are enemies, so we know the purpose is to kill them. But when the player enters the central zone of the map, the game automatically returns to the main menu. Therefore, level 3 tutorial was not working and didn't achieve its purpose. 
The proposed solution could be:
1. Use the death state of enemy as the condition to pass the tutorial

**Comment by tommy-tran** [comment]
#249
