### ISSUE TITLE
Enemy death after leaving the main platform(Bug)

### ISSUE THREAD

**Issue by JiaanZhang** [olejarza/VACATe#186]
In level two, in the puzzle of two levers and two enemies, if the enemy wasn’t killed by player’s mine but blowed out of the main platform, the puzzle can not be solved. the same situation can be applied to the second powerful boss as well.
Proposed Solution:
1. If the enemy is blowed out of the main platform, it should count as dead.

**Comment by tommy-tran** [comment]
Better if we can prevent knockback for special enemies
