### ISSUE TITLE
Wizard spell 2 moving speed recovery problem(Bug)

### ISSUE THREAD

**Issue by JiaanZhang** [olejarza/VACATe#188]
After the wizard used the second spell, the moving speed of the wizard decreased and it need almost two second to recover to the original speed. But if the player used the fire during the recovery time, the wizard moving speed can be recovered immediately. 
Proposed Solution:
1. If this is a hidden trick for higher level player, this bug can be ignored
2. If this is a real bug, the fire shouldn't be able to recover the wizard's speed or could be disabled during the recovery time

**Comment by tommy-tran** [comment]
#251
