### ISSUE TITLE
Skip Button Problem(Bug)

### ISSUE THREAD

**Issue by JiaanZhang** [olejarza/VACATe#190]
When start a new game, if you press the skip tutorial button frequently, the skip button won't work for about several seconds. Then you are allowed to enter the game, but the colour of the characters have changed. For example, if you enter the game after pressing the skip button twice, there are a red character and yellow character. If you enter the game after pressing the skip button for over three times, you will see two grey character and the wizard cannot moving at all but yer archer spell attack is allowed. Both condition has no dialogue after entering the game.
Proposed Solution:
1. Add one menu state, which limit user clicking the button for only once.

**Comment by trudeaua** [comment]
Same root cause as #139
