### ISSUE TITLE
Don't include colours that don't reflect any of the players (SUGGESTION)

### ISSUE THREAD

**Issue by tdykstra123** [olejarza/VACATe#195]
Description of Requested Feature/Change to Existing Feature
Context: The yellow rocks in the first level were confusing at first

High level feature explanation: Ensure that the colours of all of the objects match the colours of the players, and don't have anything extraneous

Rationale/Justification of Feature: May be confusing to new users, not great practice to have objects that the user cannot interact with in any way

Suggested Solutions:
Have a check that will only spawn in items of colours that match the colours of the players themselves

**Comment by tommy-tran** [comment]
Fixed in next version of levels
