### ISSUE TITLE
Add shadows to the players (SUGGESTION)

### ISSUE THREAD

**Issue by tdykstra123** [olejarza/VACATe#196]
Description of Requested Feature/Change to Existing Feature
Context: I kept falling off the green/purple bridges because I couldn't tell whether or not I was on it

High level feature explanation: Add some kind of signifier to show the player exactly where they are in 3D space

Rationale/Justification of Feature: I got very mad after the third time I fell off of the bridge, and I'm sure other players would appreciate knowing where their characters are

Suggested Solutions: 
-Add a detailed shadow underneath the players
-Add one of those circular shadows underneath the players

**Comment by tommy-tran** [comment]
Related to lighting on bridges

**Comment by tommy-tran** [comment]
#197 Since the bridge is set as a light source, shadows dont show up. Will be fixed in #249
