### ISSUE TITLE
Add more scenery to the coloured bridges in level 1 (SUGGESTION)

### ISSUE THREAD

**Issue by tdykstra123** [olejarza/VACATe#197]
Description of Requested Feature/Change to Existing Feature
Context: I was crossing the bridge in level 1, felt like I was on it forever

High level feature explanation: Add signifiers to convey to the user that they are, in fact, making progress on the bridge (and that it isn't an endless staircase situation)

Rationale/Justification of Feature: While I doubt any player would get legitimately stuck there, the lack of moving background or moving anything (besides the players) may make the user feel like they're running in place

Suggested Solutions:
-Add more scenery
-Change the design of the purple/green bridges so they're textured
-Change the path of the bridges so they aren't just straight diagonal lines

**Comment by tommy-tran** [comment]
#249 Will look into with redesign
