### ISSUE TITLE
Character Customisation (SUGGESTION)

### ISSUE THREAD

**Issue by tdykstra123** [olejarza/VACATe#199]
Description of Requested Feature/Change to Existing Feature
Context: The characters remind me of the ones from Gang Beasts, which lets you have stupid chicken hats and cowboy hats and stuff like that.

High level feature explanation: Allow for players to choose cosmetic customisations for their characters

Rationale/Justification of Feature: It will greatly help the longevity and replayability of the game, as people will want to dress up in their favourite hats and collect more hats (if you make it rewarding)

Suggested Solutions:
-Add an unlock system so the players can get more customization options
-Have several customisation options right off the bat

**Comment by tommy-tran** [comment]
Will do if time permits
