### ISSUE TITLE
More Taunts (SUGGESTION)

### ISSUE THREAD

**Issue by tdykstra123** [olejarza/VACATe#200]
Description of Requested Feature/Change to Existing Feature
Context: The taunt was a nice touch, and made me want more options.

High level feature explanation: Add more taunts that the player can either unlock or cycle through

Rationale/Justification of Feature: It's a lot of fun and will add to the longevity and replayability of the game

Suggested Solutions:
-Add a series of animations that the players can unlock
-Start the game with a series of animations that pressing the taunt button could play (make it random)
-Allow the users to choose which taunts they'll use

**Comment by tommy-tran** [comment]
Intended to be ultimate ability but not doing for now may revisit if time permits
