### ISSUE TITLE
Boss cannot attack players near the enterance (BUG)

### ISSUE THREAD

**Issue by AlexanderPattison** [olejarza/VACATe#203]
1. Description of bug
• Context – I lured the boss to the entrance, and stood the players at the entrance.
• Expected output – Be dealt damage by boss because I am able deal it damage.
• Actual output – The boss cannot deal me damage.
 
2. Minimal steps to reproduce 
• Lure boss to entrance
• Attack and deal the boss damage.

3. Appearance of bug
Boss area.
 
4. System configuration
• Very low quality, 1080 x 1920
• Windows 10
• 64-bit, Intel CPU, 32GB RAM
• PS3 controller, using driver: SCP-DS-Driver-Package-1.2.0.160

**Comment by tommy-tran** [comment]
#208
