### ISSUE TITLE
Players cannot deal damage to enemies near enterance (BUG)

### ISSUE THREAD

**Issue by AlexanderPattison** [olejarza/VACATe#204]
Description of bug
• Context – I try to deal damage to the enemies near the start gate.
• Expected output – Deal the enemies damage.
• Actual output – I cannot deal them damage, but they can deal me damage.

Minimal steps to reproduce
• Stand near the entrance with an enemy
• Attack enemy

Appearance of bug
All enemy areas (excluding boss).

System configuration
• Very low quality, 1080 x 1920
• Windows 10
• 64-bit, Intel CPU, 32GB RAM
• PS3 controller, using driver: SCP-DS-Driver-Package-1.2.0.160

Suggestion:
Enemies do not path near entrance, and return back to an origination point.

**Comment by tommy-tran** [comment]
encompassed in #208
