### ISSUE TITLE
Player health regeneration or damage protection (SUGGESTION)

### ISSUE THREAD

**Issue by AlexanderPattison** [olejarza/VACATe#205]
Description of Requested Feature/Change to Existing Feature
Context: After fighting enemies, the player health is low. There are no opportunities to improve the player's ability to protect or regenerate health (unlocks or usable items).
High level feature explanation: Health regeneration, damage protection (armour).
Rationale/Justification of Feature
There is no way to regenerate health, or have damage protection from items.

**Comment by tommy-tran** [comment]
#251 
Characters do heal but at a slow rate. Will be tweaking higher for a better experience
