### ISSUE TITLE
Quit to main menu (SUGGESTION)

### ISSUE THREAD

**Issue by AlexanderPattison** [olejarza/VACATe#206]
Description of Requested Feature/Change to Existing Feature
Context: When in-game, there is no way to exit.
High level feature explanation: Menu accessible by a key (esc), where there is a 'Quit to main menu' button.
Rationale/Justification of Feature
The player should be able to exit the level and use the main menu.

**Comment by trudeaua** [comment]
Can exit to menu from in-game pause menu in #244 but can't fully use the menu yet
