### ISSUE TITLE
Quit the program from in-game (SUGGESTION)

### ISSUE THREAD

**Issue by AlexanderPattison** [olejarza/VACATe#207]
Description of Requested Feature/Change to Existing Feature
Context: When in-game, the player cannot exit the program.
High level feature explanation: A menu is accessible by a key (esc), where there is a 'Quit' button.
Rationale/Justification of Feature
The player should be able to exit the program from in-game.

**Comment by trudeaua** [comment]
Added pause menu with this functionality in #244
