### ISSUE TITLE
Hint for the difficult puzzle (SUGGESTIONS)

### ISSUE THREAD

**Issue by ApocKira** [olejarza/VACATe#235]
Give the hint when character enter a different room with puzzle, to give players a direction to solve the puzzles in the room.

**Comment by tommy-tran** [comment]
Perhaps a timer can be placed on players stuck in a room with a puzzle still active, we can trigger dialogue to give them a hint.

**Comment by tommy-tran** [comment]
Decided to simplify game puzzles. Will bring back if this is still an issue
