### ISSUE TITLE
Add enemy tracking for Tutorial Room 3

### ISSUE THREAD

**Issue by nessa-art** [olejarza/VACATe#28]
In the tutorial, players will be required to kill all enemies in Room 3. The door to Room 4 should only unlock if all enemies in Room 3 have been demolished. 

What's needed:
- A way to track the states of all enemies in Room 3, and to only unlock the door if all enemies are dead.

**Comment by camvr** [comment]
Just some input on this issue: The enemies really only have two retrievable states, either they're alive or dead. To check if this you can use `enemy.GetComponent<EntityStatController>.isDead` which is a boolean value

**Comment by nessa-art** [comment]
Thanks for the input Cam! That was how I was planning to go about it after exploring the code.
