### ISSUE TITLE
Player Death animation goes back to Idle after animation finished

### ISSUE THREAD

**Issue by camvr** [olejarza/VACATe#34]
When the player dies there is a delay before their corpse disappears from the world, however when they die the animation shows them falling then instantly goes back to a standing position. Could we have the player stayed laying down after dying?

**Comment by trudeaua** [comment]
Yeah that was caused by the animator controller going from Die->Exit and back to Entry->Idle (does that automatically). After removing the transition from Die->Exit they stop moving so that should be good for the demo.

Another option is to replace the character with a ragdoll upon death

**Comment by camvr** [comment]
I actually really like the idea of replacing the character with a ragdoll upon death. Do you know how to do that? Would we just turn them to a ragdoll upon death or after the death animation?

**Comment by trudeaua** [comment]
Right after the animation finishes we'd replace with a ragdoll. I'll do some research
