### ISSUE TITLE
PlayerMotorController.cs: Parameter 'Charge' does not exist

### ISSUE THREAD

**Issue by camvr** [olejarza/VACATe#46]
When running the scene with a player class *other than* the ranger, this error is constantly spit out. Since the 'Charge' parameter is checked in the `PlayerMotorController` class (which is a shared component), we have a few options:
1. Add a 'Charge' parameter to all the other animation controllers (not ideal)
2. Add a check in `PlayerMotorController` ensuring that the current player is a ranger (I don't like this)
3. Modify the AC to not use this variable

Building onto the 3rd option, perhaps we could make the ranger's 'PrimaryAttack' trigger actually be a bool to signify that its "charging", then in order to transfer to the released animation state we require 'PrimaryAttack' to be false. This would be in line with the way the primary attack animation is triggered for the ranger class, and this could be used in a similar manner for the mage's primary attack as well. Let me know what you think.

**Comment by trudeaua** [comment]
Yeah we could just change primary attack to a bool, and have it charge for everyone? Could be a new mechanic

**Comment by camvr** [comment]
I wouldn't say a new mechanic, but rather just re-architecting the animation controller for classes that have animations that have a state of being "held". For instance we will need to do something similar for the mage too

**Comment by trudeaua** [comment]
Fixed by replacing all PrimaryAttack and SecondaryAttack triggers with booleans. Most attack animations now have a "Charge" and "Release" state, for example setting "PrimaryAttack" to `true` triggers the "Charge" animation, and setting it to `false` triggers the "Release" animation.
