### ISSUE TITLE
Create combat controllers for each enemy

### ISSUE THREAD

**Issue by trudeaua** [olejarza/VACATe#76]
- Caused by not all enemy ACs having a "Stab Attack" trigger. Only the Metalon has the "Stab Attack" trigger for its primary attack
- Must redo all enemy ACs so that they use the same parameters

**Edit**: In EnemyCombatController.cs, the only the Metalon has the "Stab Attack" trigger for its primary attack. We must create combat controllers for all enemies so their correct animations are played

**Comment by camvr** [comment]
Delivered in #88
