### ISSUE TITLE
Player Rotation Rotates the CameraBillboard along the Y axis

### ISSUE THREAD

**Issue by camvr** [olejarza/VACATe#85]
Genuinely unsure of why this is suddenly happening, I don't remember it being a thing in the demo. But when the player rotates, it causes this weird local rotation of the camera billboard.

**Comment by tommy-tran** [comment]
Looks like its from the changes done here:
https://github.com/olejarza/VACATe/commit/92f1776aa001a37c3ed0d4be25f1cd40a20d3855#diff-394b4783801bc8057804067a6d9ea925

Will reverting this change affect anything?

**Comment by camvr** [comment]
Yep this was my fault... Among all the issues I had then, one of them was `Camera.main` returning null for whatever reason, so I made a quick fix so I could move on with the input mocking... Forgot about it shortly after lol
